doctrine_migrations:
    migrations_paths:
        DoctrineMigrations: '%kernel.project_dir%/migrations'
    # Remove or comment out the storage section below
    # storage:
    #     table_storage:
    #         table_name: migration_versions_new