# config/packages/security.yaml
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Define role hierarchy - allows higher roles to inherit permissions
    role_hierarchy:
        ROLE_SUPER_ADMINISTRATOR: [ROLE_ADMINISTRATOR, ROLE_JURY, ROLE_CANDIDATE]
        ROLE_ADMINISTRATOR: [ROLE_JURY, ROLE_CANDIDATE]
        ROLE_JURY: [ROLE_CANDIDATE]
        ROLE_CANDIDATE: []

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                always_remember_me: false
            form_login:
                login_path: login_index
                check_path: login_check
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                default_target_path: login_success
                always_use_default_target_path: true
            logout:
                path: login_logout
                target: home_index
                invalidate_session: true
                clear_site_data: ['cookies', 'storage']

    # Easy way to control access for large sections of your site
    access_control:
        # Admin routes
        - { path: ^/admin/super, roles: ROLE_SUPER_ADMINISTRATOR }
        - { path: ^/admin, roles: ROLE_ADMINISTRATOR }

        # Jury routes
        - { path: ^/jury, roles: ROLE_JURY }

        # Candidate routes - protected but accessible to candidates and above
        - { path: ^/candidate/profile, roles: ROLE_CANDIDATE }
        - { path: ^/candidate/applications, roles: ROLE_CANDIDATE }

        # Public routes - accessible to anyone
        - { path: ^/candidate$, roles: PUBLIC_ACCESS }
        - { path: ^/candidate/start_candidate, roles: ROLE_CANDIDATE }
        - { path: ^/candidate/profile, roles: ROLE_CANDIDATE }

        - { path: ^/presentation, roles: PUBLIC_ACCESS }
        - { path: ^/contact, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon