# config/services.yaml (main file, not in packages directory)
parameters:
  # Your existing parameters...
  student_card_directory: '%kernel.project_dir%/private/uploads/student_cards'

  # Add this parameter for email service
  app.from_email: '%env(MAILER_FROM_EMAIL)%'

services:
  # default configuration
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Configure EmailService with the from email parameter
  App\Service\EmailService:
    arguments:
      $fromEmail: '%app.from_email%'